[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ticketwatcher"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["requests"]

[tool.setuptools.packages.find]
where = ["src"]