name: TicketWatcher

on:
  issues:
    types: [opened, reopened, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch: {}

permissions:
  contents: write       # to push a branch and create files
  pull-requests: write  # to open draft PRs
  issues: write         # to comment/label
  # actions: read       # (optional) if you later want to read CI status

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f pyproject.toml ]; then pip install -e .; else pip install -r requirements.txt; fi

      - name: Run TicketWatcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # auto-provided
          TICKETWATCHER_TRIGGER_LABELS: agent-fix,auto-pr
          TICKETWATCHER_BRANCH_PREFIX: agent-fix/
        run: |
          python -m ticketwatcher --event-file "$GITHUB_EVENT_PATH"
